# Generated by Django 4.1.5 on 2023-01-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapi', '0003_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
