# Generated by Django 4.1.5 on 2023-01-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapi', '0006_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
