# Generated by Django 4.1.5 on 2023-01-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapi', '0007_remove_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
